### ISSUE TITLE
import Promise from 'bluebird';

### ISSUE THREAD

**Issue by CipherSam** [amilajack/node-openvpn#3]
import Promise from 'bluebird';
SyntaxError: Unexpected identifier

Just like your openvpn-bin which you fixed, the same thing is happening here. Are you willing to fix this?

Thanks.

**Comment by amilajack** [comment]
Implementing this should be similar to like it was in the other repo. I’d love if you can contribute to this by looking at the changes that I have made to the other project. Unfortunately I am really busy at the moment so I won’t be able to look into this right now but I will be able to review and merge your PR. Thanks!

**Comment by CipherSam** [comment]
Let me know when you can. I'm a bit overwhelmed by the like 30 changes 😛
